spring.application.name=building

# ================= DATABASE (DOCKER SAFE) =================
spring.datasource.url=jdbc:postgresql://postgres:5432/building_db
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ================= JPA =================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# ================= LOGGING (clean terminal) =================
logging.level.root=WARN
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.level.org.springframework=WARN

# optional (helps avoid lazy init confusion in dev)
spring.jpa.open-in-view=false